
version: "3.8"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart:  on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: on-failure
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@domain-name.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
